jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

db:
  num: 1
  url:
    '0': jdbc:mysql://@MYSQL-HOST@:@MYSQL-PORT@/@MYSQL-DB@?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
  user: @MYSQL-USERNAME@
  password: @MYSQL-PASSWORD@
management:
  metrics:
    export:
      elastic:
        enabled: false
      influx:
        enabled: false
nacos:
  core:
    auth:
      caching:
        enabled: true
      enable:
        userAgentAuthWhite: false
      enabled: false
      plugin:
        nacos:
          token:
            expire:
              seconds: 18000
            secret:
              key: SecretKey012345678901234567890123456789012345678901234567890123456789
      server:
        identity:
          key: serverIdentity
          value: security
      system:
        type: nacos
  istio:
    mcp:
      server:
        enabled: false
  naming:
    empty-service:
      auto-clean: true
      clean:
        initial-delay-ms: 50000
        period-time-ms: 30000
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
server:
  error:
    include-message: always
  port: 8848
  servlet:
    contextPath: /nacos
  tomcat:
    accesslog:
      enabled: true
      max-days: 30
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i'
    basedir: logs
spring:
  sql:
    init:
      platform: mysql