# 赞助
github: KouShenhai
patreon: KouShenhai
open_collective: KouShenhai
ko_fi: KouShenhai
tidelift: maven
community_bridge: KCloud-Platform-IoT
liberapay: KouShenhai
issuehunt: KouShenhai
otechie: KouShenhai
lfx_crowdfunding: KouShenhai
custom: https://github.com/KouShenhai
