server:
  port: 9032

spring:
  application:
    name: laokou-sample-websocket
  tcp-server:
    enabled: false
  websocket-server:
    enabled: true
    boss-core-size: 2
    core-pool-size: 16
    worker-core-size: 16
    ip: 0.0.0.0
    port: 1112
    service-id: ${spring.application.name}-server
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    suffix: .html
    prefix: classpath:/templates/

rocketmq:
  producer:
    group: laokou_producer_group
  name-server: rocketmq-namesrv:9876
  consumer:
    pull-batch-size: 16

logging:
  config: classpath:log4j2.xml
