server:
  port: 5000
  address: 192.168.62.1
  servlet:
    context-path: /monitor
  connection-timeout: 60000
  tomcat:
    max-http-header-size: -1
    max-connections: -1
    max-http-post-size: -1
    max-threads: -1
spring:
  profiles:
    active: test
  application:
    name: laokou-monitor
  security:
    user:
      name: root
      password: koushenhai
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
