server:
  port: 5000
  address: 10.0.8.7
  servlet:
    context-path: /monitor
  connection-timeout: 60000
  tomcat:
    max-http-header-size: -1
    max-connections: -1
    max-http-post-size: -1
    max-threads: -1