server:
  port: 5000
  servlet:
    context-path: /monitor
  tomcat:
    max-connections: -1
    connection-timeout: 600000

# spring
spring:
  application:
    name: @artifactId@
  # dev|test|prod
  profiles:
    active: @profile.active@