spring:
  profiles:
    active: @profile.active@
  application:
    name: laokou-monitor
  security:
    user:
      name: root
      password: koushenhai
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always