server:
  port: 5000
  address: 192.168.62.1
  servlet:
    context-path: /monitor
spring:
  profiles:
    active: test
  application:
    name: laokou-monitor
  security:
    user:
      name: root
      password: koushenhai
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
