server:
  port: 5000
  address: 127.0.0.1
  servlet:
    context-path: /monitor
  tomcat:
    max-http-header-size: -1
    max-connections: -1
    max-threads: -1
    max-http-form-post-size: -1
    connection-timeout: 60000