version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.4

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout
      - run: mvn clean test -P prod
      - run: mvn clean install -P prod -DskipTests -B
workflows:
  maven-build:
    jobs:
      - build
