version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.5

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout
      - run: ./gradlew build
workflows:
  maven-build:
    jobs:
      - build
