
spring:
  application:
    name: laokou-generator
  profiles:
    # 环境 dev|test|prod
    active: test
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl