# server
server:
  port: 10006

# spring
spring:
  profiles:
    # dev|test|prod
    active: @profile.active@

# feign
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000