server:
  port: 8888

rocketmq:
  producer:
    group: laokou-producer-group
  name-server: laokou.org:9876

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.62.144:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: