version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch8/data:/usr/share/elasticsearch/data
      - ./elasticsearch8/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch8/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=laokou123
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    network_mode: bridge
    ulimits:
      memlock:
        soft: -1
        hard: -1