server:
  port: 8086

spring:
  rabbitmq:
    port: 5672
    host: 192.168.30.130
    username: root
    password: laokou123
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true