# server
server:
  port: 9999
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true

# spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    # 解决集成sentinel，openfeign启动报错，官方下个版本修复
    openfeign:
      lazy-attributes-resolution: true
    # sentinel
    sentinel:
      datasource:
        db0:
          nacos:
            server-addr: @NACOS-CONFIG-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            group-id: LAOKOU_GROUP
            data-id: admin-sentinel.json
            data-type: json
            rule-type: flow
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*