# tomcat
server:
  port: 5555
  tomcat:
    connection-timeout: 600000
  compression:
    enabled: true

# spring
spring:
  application:
    name: @pom.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    # gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: admin
        url: /v3/api-docs/admin
      - name: auth
        url: /v3/api-docs/auth
      - name: oss
        url: /v3/api-docs/oss

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# feign
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000

# 忽略uris
ignore:
  uris:
    - /oauth2/password/captcha
    - /actuator/**
    - /ws/**
    - /favicon.ico
    - /swagger-ui/**
    - /swagger-ui.html
    - /**/v3/api-docs/**
