#   /*
#    * Copyright (c) 2022 KCloud-Platform-Alibaba Author or Authors. All Rights Reserved.
#    *
#    * Licensed under the Apache License, Version 2.0 (the "License");
#    * you may not use this file except in compliance with the License.
#    * You may obtain a copy of the License at
#    *
#    *   http://www.apache.org/licenses/LICENSE-2.0
#    *
#    * Unless required by applicable law or agreed to in writing, software
#    * distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.
#    *
#    */
server:
  port: 5555
  # 开启请求压缩
  compression:
    enabled: true
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
    # 证书密码
    key-password: laokou
  http2:
    enabled: @SSL-ENABLED@
  forward-headers-strategy: native
  # 优雅停机
  shutdown: graceful
  netty:
    # 请求的最大初始行长度
    max-initial-line-length: 4096
# spring
spring:
  application:
    name: @pom.artifactId@
  profiles:
    # dev|test|prod
    active: @PROFILE-ACTIVE@
  webflux:
    multipart:
      max-parts: -1
      max-disk-usage-per-part: -1
      max-in-memory-size: 4096
  cloud:
    # sentinel
    sentinel:
      filter:
        enabled: true
      datasource:
        # key可以自定义
        db0:
          nacos:
            server-addr: @NACOS-DISCOVERY-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            data-id: gateway-flow.json
            rule-type: gw_flow # 网关规则
            group-id: @NACOS-GROUP@
            data-type: json
    # loadbalancer
    loadbalancer:
      # 开启缓存，从本地内存里面取
      # 关闭缓存，从redis里面取
      cache:
        caffeine:
          spec: initialCapacity=4096,expireAfterWrite=30s
        enabled: true
      nacos:
        # 开启Nacos路由负载均衡
        enabled: true
    # network
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
    # gateway
    gateway:
      discovery:
        locator:
          # 关闭动态生成路由
          enabled: false
          # 开启服务ID强制小写
          lower-case-service-id: true
      httpclient:
        ssl:
          # 信任所有下游证书
          use-insecure-trust-manager: true
        # 关闭netty日志
        wiretap: false
        pool:
          # 连接池中连接的最大空闲时间
          max-idle-time: 10m
          # 最大连接数
          max-connections: 10000
          # 连接池中连接的最大存活时间
          max-life-time: 5m
          # elastic   无线扩展的线程池（弹性线程池，连接数不可控）
          # fixed     固定数量线程池
          # disabled  不使用线程池（只有一个线程）
          type: fixed
          # 线程池获取连接最大等待时间（毫秒）
          acquire-timeout: 60000
        # 连接超时时间
        connect-timeout: 60000
      httpserver:
        # 关闭netty日志
        wiretap: false

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml