server:
  compression:
    # 开启压缩
    enabled: true
    # 配置支持压缩 MIME-TYPE
    mime-types: text/html,text/xml,text/plain,application/xml,application/json,application/x-www-form-urlencoded
  address: 127.0.0.1
  port: 5555
  max-http-header-size: -1
  tomcat:
    max-http-post-size: -1

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000/monitor
        username: root
        password: koushenhai
        instance:
          service-base-url: http://127.0.0.1:${server.port}
          prefer-ip: true

logging:
  file: logs/${spring.application.name}/info.log

laokou:
  uris:
    - /sys/auth/api/captcha
    - /sys/auth/api/login
    - /sys/auth/api/zfbLogin
    - /actuator/**
    - /swagger/api-docs
    - /swagger-resources/**
    - /swagger-ui.html
    - /v2/api-docs
    - /webjars/**
    - /druid/**
