# tomcat
server:
  port: 5555
  tomcat:
    connection-timeout: 600000
  compression:
    enabled: true

# spring
spring:
  application:
    name: @pom.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    # sentinel
    sentinel:
      filter:
        enabled: true
      datasource:
        # key可以自定义
        db0:
          nacos:
            server-addr: @NACOS-DISCOVERY-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            data-id: gateway-sentinel.json
            rule-type: gw_flow # 网关规则
            group-id: LAOKOU_GROUP
            data-type: json
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    # gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true