jasypt:
  encryptor:
    password: koushenhai5201314wumeihua
spring:
  application:
    name: laokou-gateway
  messages:
    encoding: UTF-8
    basename: i18n/messages
  profiles:
    active: test
  main:
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: -1
      enabled: true
      max-request-size: -1
      file-size-threshold: -1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    gateway:
      routes:
        - id: LAOKOU-ADMIN
          uri: lb://laokou-admin
          predicates:
          - Path=/admin/**
          filters:
          - StripPrefix=1
          # 限流
          - name: RequestRateLimiter #请求数限流
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1000
              redis-rate-limiter.burstCapacity: 3000
          # 降级
          - name: Hystrix
            args:
              name: default
              # 降级接口地址
              fallbackUri: 'forward:/fallback'
        - id: LAOKOU-AUTH
          uri: lb://laokou-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            # 限流
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 3000
            # 降级
            - name: Hystrix
              args:
                name: default
                # 降级接口地址
                fallbackUri: 'forward:/fallback'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000
          #hystrix配置隔离策略为信号量模式
          strategy: SEMAPHORE
          #增加并发量设置（默认是10）
          semaphore:
            maxConcurrentRequests: 30000

feign:
  httpclient:
    # 开启httpclient
    enable: ture
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gateway:
  swagger:
    routes:
      - name: laokou-admin
        location: /admin
      - name: laokou-auth
        location: /auth
  uris:
    - /sys/auth/api/captcha
    - /sys/auth/api/login
    - /sys/auth/api/zfbLogin
    - /workflow/definition/api/image
    - /workflow/task/api/diagram
    - /actuator/**
    - /swagger/api-docs
    - /swagger-resources/**
    - /doc.html
    - /v2/api-docs
    - /webjars/**
    - /druid/**
