jasypt:
  encryptor:
    password: koushenhai5201314wumeihua
spring:
  application:
    name: laokou-gateway
  messages:
    encoding: UTF-8
    basename: i18n/messages
  profiles:
    active: @profile.active@
  main:
    lazy-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000
          #hystrix配置隔离策略为信号量模式
          strategy: SEMAPHORE
          #增加并发量设置（默认是10）
          semaphore:
            maxConcurrentRequests: 30000

feign:
  httpclient:
    # 开启httpclient
    enable: ture
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gateway:
  swagger:
    routes:
      - name: laokou-admin
        location: /admin
      - name: laokou-auth
        location: /auth
  uris:
    - /sys/auth/api/captcha
    - /sys/auth/api/login
    - /sys/auth/api/zfbLogin
    - /actuator/**
    - /swagger/api-docs
    - /swagger-resources/**
    - /doc.html
    - /v2/api-docs
    - /webjars/**
    - /druid/**
    - /ws/**
    - /sys/auth/api/open/login
    - /sys/login.html