server:
  address: 192.168.62.1
  port: 5555
  max-http-header-size: -1
  tomcat:
    max-http-post-size: -1

spring:
  application:
    name: laokou-gateway
  messages:
    encoding: UTF-8
    basename: i18n/messages
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: -1
      enabled: true
      max-request-size: -1
      file-size-threshold: -1
  cloud:
    gateway:
      routes:
        - id: LAOKOU-ADMIN
          uri: lb://laokou-admin
          predicates:
          - Path=/admin/**
          filters:
          - SwaggerHeaderFilter
          - StripPrefix=1
          - name: RequestRateLimiter #请求数限流
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1000
              redis-rate-limiter.burstCapacity: 3000

laokou:
  uris:
    - /sys/auth/api/captcha
    - /sys/auth/api/login
    - /sys/auth/api/zfbLogin
    - /actuator/**
    - /swagger/api-docs
    - /swagger-resources/**
    - /swagger-ui.html
    - /v2/api-docs
    - /webjars/**
    - /druid/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000
          #hystrix配置隔离策略为信号量模式
          strategy: SEMAPHORE
          #增加并发量设置（默认是10）
          semaphore:
            maxConcurrentRequests: 30000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
