
#spring
spring:
  profiles:
    # 环境 dev|test|prod
    active: test
  application:
    name: laokou-log
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl