server:
  port: 8888

spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath*:db/changelog/changelog.sql
    user: root
    password: koushenhai123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://laokou.org:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    drop-first: true
    default-schema: test
    enabled: true