# server
server:
  port: 10007
  tomcat:
    connection-timeout: 600000

#spring
spring:
  profiles:
    # dev|test|prod
    active: @profile.active@
  # i18n
  messages:
    basename: i18n/messages
  servlet:
    # multipart
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

# log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: @mybatis-plus.log-impl@