# server
server:
  port: 10007
  tomcat:
    connection-timeout: 600000

#spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  # i18n
  messages:
    basename: i18n/messages
  servlet:
    # multipart
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*