server:
  port: 10005
  shutdown: graceful
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou

spring:
  freemarker:
    check-template-location: false
  application:
    name: @pom.parent.artifactId@
  tcp:
    ip: 0.0.0.0
    port: 1001
    app-name: ${spring.application.name}-server
  mqtt:
    enabled: false
    username: emqx
    password: laokou123
    client-id: S&D1PGLPG58KZ2&89&1
    host: tcp://192.168.1.147:1883
    topics:
      - test
      - /55/D1PGLPG58KZ2/function/get
      - /55/D1PGLPG58KZ2/info/get
      - /55/D1PGLPG58KZ2/ota/get
      - /55/D1PGLPG58KZ2/upgrade/get
      - /55/D1PGLPG58KZ2/monitor/get
      - /55/D1PGLPG58KZ2/ntp/get
  datasource:
    dynamic:
      strict: false
      datasource:
        td:
          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
          url: jdbc:TAOS-RS://tdengine.laokou.org:6041/kcloud_platform_iot?useSSL=false
          username: root
          password: taosdata
