server:
  port: 10005
  shutdown: graceful
  ssl:
    enabled: false

spring:
  application:
    name: ${spring.tcp.app-name}-server
  tcp:
    ip: 0.0.0.0
    port: 1001
    app-name: @pom.parent.artifactId@
  mqtt:
    enabled: true
    username: emqx
    password: laokou123
    client-id: S&D1PGLPG58KZ2&89&1
    host: tcp://192.168.1.229:1883
    topics:
      - test
      - /55/D1PGLPG58KZ2/function/get
      - /55/D1PGLPG58KZ2/info/get
      - /55/D1PGLPG58KZ2/ota/get
      - /55/D1PGLPG58KZ2/upgrade/get
      - /55/D1PGLPG58KZ2/monitor/get
      - /55/D1PGLPG58KZ2/ntp/get
