server:
  port: 10005
  shutdown: graceful

spring:
  application:
    name: @pom.parent.artifactId@
  mqtt:
    username: emqx
    password: laokou123
    host: tcp://192.168.1.204:1883
    topics:
      - test
