server:
  port: 10005
  shutdown: graceful

spring:
  application:
    name: @pom.parent.artifactId@
  mqtt:
    username: mqtt
    password: laokou123
    host: tcp://127.0.0.1:1883
    topics:
      - test