server:
  port: 10005
  shutdown: graceful

spring:
  application:
    name: @pom.parent.artifactId@
  mqtt:
    username: emqx
    password: laokou123
    client-id: S&D1PGLPG58KZ2&89&1
    host: tcp://192.168.1.204:1883
    topics:
      - test
      - /55/D1PGLPG58KZ2/function/get
      - /55/D1PGLPG58KZ2/info/get
      - /55/D1PGLPG58KZ2/ota/get
      - /55/D1PGLPG58KZ2/upgrade/get
      - /55/D1PGLPG58KZ2/monitor/get
      - /55/D1PGLPG58KZ2/ntp/get
