server:
  port: 8087
spring:
  application:
    name: laokou-test-container-dubbo-consumer
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 1113
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    address: nacos://@NACOS-DISCOVERY-ADDRESS@
    username: @NACOS-USERNAME@
    password: @NACOS-PASSWORD@
    group: TEST_GROUP
    parameters:
      namespace: @NACOS-NAMESPACE@
      register-consumer-url: true
    protocol: nacos
