# server
server:
  port: 1111
  servlet:
    encoding:
      charset: UTF-8
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true

# spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  # i18n
  messages:
    basename: i18n/messages
  cloud:
    # 解决集成sentinel，openfeign启动报错，官方下个版本修复
    openfeign:
      lazy-attributes-resolution: true
    # sentinel
    sentinel:
      filter:
        enabled: true
      datasource:
        # 自定义名称
        db0:
          nacos:
            server-addr: @NACOS-CONFIG-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            data-id: auth-sentinel.json
            data-type: json
            group-id: LAOKOU_GROUP
            rule-type: flow
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*