# server
server:
  port: 1111
  servlet:
    encoding:
      charset: UTF-8
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true

# spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  # i18n
  messages:
    basename: i18n/messages
  cloud:
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*