# server
server:
  port: 1111
  servlet:
    encoding:
      charset: UTF-8

# spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # dev|test|prod
    active: @profile.active@
  # i18n
  messages:
    basename: i18n/messages
  cloud:
    # sentinel
    sentinel:
      filter:
        enabled: true
      datasource:
        # 自定义名称
        db0:
          nacos:
            server-addr: @NACOS-CONFIG-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            data-id: auth-sentinel.json
            data-type: json
            group-id: LAOKOU_GROUP
            rule-type: flow
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*