# server
server:
  port: 10005

#spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*