server:
  port: 10001
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: @pom.parent.artifactId@
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: false
#spring
spring:
  websocket:
    port: 7777
    app-name: @pom.parent.artifactId@
    pool-name: "laokou-websocket-pool"
  application:
    name: ${spring.websocket.app-name}-server
  profiles:
    # 环境 dev|test|prod
    active: @PROFILE-ACTIVE@
  webflux:
    multipart:
      max-in-memory-size: 512
      max-parts: -1
      max-disk-usage-per-part: -1
      max-headers-size: 20
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
